name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies for Client
        run: |
          cd client
          npm install

      - name: Build Client
        run: |
          cd client
          npm run build

      - name: Install Dependencies for Server
        run: |
          cd server
          npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/Bargainwale
            git pull origin main

            # Deploy Client
            cd client
            npm install
            npm run build

            # Deploy Server
            cd ../server
            npm install
            pm2 restart server
            pm2 save
            sudo systemctl restart nginx